# Generated by Django 3.2.23 on 2023-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=6),
        ),
    ]
